# 로컬 적용 방법:
#   kubectl create secret generic postgres-secret \
#     --from-literal=postgres-db=devopsim \
#     --from-literal=postgres-user=devopsim \
#     --from-literal=postgres-password=devopsim
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  postgres-db: ""
  postgres-user: ""
  postgres-password: ""
