apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api
  namespace: api
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infra/helm/api
      valuesFiles:
        - infra/helm/api/values.yaml
        - infra/helm/api/values-production.yaml
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
