image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "db"  # Service 이름을 db로 고정 (api가 @db:5432로 접근)

auth:
  secretName: postgres-secret
  username: devopsim

service:
  port: 5432

storage: 1Gi
