apiVersion: networking.k8s.io/v1
kind: Ingress # nginx를 쓴다
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: devopsim
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
# L4
# kind: Ingress vs Service: lb
