replicaCount: 2

image:
  repository: 893286712531.dkr.ecr.us-east-2.amazonaws.com/devopsim/api
  tag: "0.9.1"
  pullPolicy: Always

redis:
  url: "redis://redis.redis.svc.cluster.local:6379"

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  className: alb
  host: ""
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

topologySpread:
  enabled: true
  maxSkew: 1
  whenUnsatisfiable: ScheduleAnyway

reloader:
  enabled: true
  secrets: api-secret
