replicaCount: 2

image:
  repository: 893286712531.dkr.ecr.us-east-2.amazonaws.com/devopsim/api
  tag: "0.3.0"
  pullPolicy: Always

ingress:
  enabled: true
  className: alb
  host: ""
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
