apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - migrate-job.yaml

labels:
  - pairs:
      version: "0.0.1"
      environment: local
    includeSelectors: false

replicas:
  - name: api
    count: 3

images:
  - name: devopsim-api
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
    target:
      kind: Deployment
      name: api # metadata.name 으로 매핑
